### ISSUE TITLE
Error: cannot open file: nimarchive/archive

### ISSUE THREAD

**Issue by melMass** [genotrance/nimarchive#1]
On OSX I cannot install using nimble.
Trying to build from source now.

**Comment by genotrance** [comment]
Looks like nimble install is not installing the generated files again. I'll look into this. In the interim, you could:

```
git clone https://github.com/genotrance/nimarchive
cd nimarchive
nimble setup
nimble install -y
```

**Comment by genotrance** [comment]
Well, this is still not fixed, but at least nimble will accept:

`nimble install nimarchive@#head`

https://github.com/nim-lang/nimble/issues/549

**Comment by melMass** [comment]
Thanks it does works using head ! Following nim-lang/nimble#549 thanks

**Comment by melMass** [comment]
I would like to pick specific items of a 7z archive but running the test `nimarchive`I get the following:

```ruby
pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
SIGABRT: Abnormal termination.
```

**Comment by melMass** [comment]
I can open a new issue if you prefer of course !

**Comment by genotrance** [comment]
Can you post a snippet? I'm also on https://gitter.im/nimterop/Lobby if you want to chat.

**Comment by genotrance** [comment]
Closing this since nimarchive now uses nimterop.
