### ISSUE TITLE
Acces to the constant AE_IFREG

### ISSUE THREAD

**Issue by EchoPouet** [genotrance/nimarchive#8]
Hello,

I can't use the constant **AE_IFREG** and it doesn't exist in your documentation. It is defined in **libarchive/archive_entry.h** file.

Thanks.

**Comment by genotrance** [comment]
```c
#define AE_IFREG	((__LA_MODE_T)0100000)
```

They are being cast so nimterop does not recognize them.

**Comment by genotrance** [comment]
This is fixed with v0.4.0.
